---
galaxy_info:
  author: author
  description: description
  license: MIT

  min_ansible_version: "2.13"

  platforms:
    - name: Debian
      versions:
        - bullseye
        - buster
    - name: Ubuntu
      versions:
        - jammy
        - focal

dependencies: []
