---
name: Molecule

"on":
  pull_request:

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    env:
      PY_COLORS: "1"
      ANSIBLE_FORCE_COLOR: "1"
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3

      - name: Setup Molecule
        uses: bec-galaxy/setup-molecule@v1

      - name: Run Molecule tests
        run: molecule test
