---
name: Release

"on":
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3

      # - name: Ansible Publish
      #   uses: ansible/ansible-publish-action@v1.0.0
      #   with:
      #     api_key: ${{ secrets.GALAXY_TOKEN }}
